### ISSUE TITLE
Steps to compile

### ISSUE THREAD

**Issue by vjega** [robamler/mupdf-nacl#1]
Hi Robamler,

It is a nice work. I have a requirement to write a custom pdf reader that should work inside browser.
It appears to be awesome project.
Please add instruction of how to compile and use this Native Client MuPDF inside Chrome. 
Do I need NaCl SDK? 
Which compiler to use. VC++, GCC, CLANG?
What about required manifest files. Are they available with this fork?

Thanks in advance

**Comment by robamler** [comment]
Hi vjega,

At the moment, this project is only a port of the core library of muPdf to NaCl. There's no visual front-end. I'm using the muPdf library in my NaCl port of a different program, k2pdfopt, see https://github.com/robamler/k2pdfopt-nacl. You can find compilation instructions in the README.md file of that project. The muPdf library is compiled in steps 1 and 2 under "Compilation". You should also consider the "Prerequisites".

Thanks for reminding me that I forgot to provide compilation instructions for this project, though. I now added a small README.md file.

If you decide to build a visual front-end that talks to this NaCl port of muPdf then I would be happy to accept your contributions. Actually, I'm even open to transferring ownership of this project to you, if that's something that can be done on Github. If you're just looking for an easy way to display a PDF inside some web-app, then Mozilla's pdf.js may be an easier solution though (but be aware that it still renders some PDFs incorrectly).

Please re-open if you're having compilation issues.

**Comment by vjega** [comment]
Thanks for the immediate reply. I evaluated pdf.js and it wont suite my clients requirement. I initially modified SumatraPDF with NPAPI for windows. The client now requires this into OSX and want to run this program on Chrome too(Chrome stopped supporting NPAPI). I would appreciate, If you could suggest me some quick fix. Else I have to port the visual part of myPDF on my own. I would send a PR if I do so.

Jega

**Comment by robamler** [comment]
Sorry for the late response. The only alternatives that come to my mind are:
- Rendering the PDF on the server side and sending the pages over as PNG. I think this is what Gmail does, except that they also seem to send over the text content and its coordinates as meta data in order to support text highlighting and copying.
- Using an iframe for the PDF (not sure if this works, but should be quite easy to test).
- Look around what other people do: Dropbox seems to render PDFs using JavaScript (not sure if they use pdf.js or a different library). Some websites of scientific journals display PDFs within each article's website if you're logged in (most of them seem to resort to server-side rendering).
